### ISSUE TITLE
Percentage position

### ISSUE THREAD

**Issue by ai** [win0err/gnome-runcat#1]
![20200421155154](https://user-images.githubusercontent.com/19343/79907716-0d7a6d80-83e8-11ea-86e0-0e7d6bf9f97b.png)

Fedora 32, GNOME 3.36, default theme and font and I switched all other extensions

**Comment by win0err** [comment]
Thank you for your feedback!

In GNOME 3.36 layout was broken. 
Fixed in RunCat release 6 (will be available at [extensions.gnome.org](https://extensions.gnome.org/extension/2986/runcat/) after review). 

Image smoothing (anti-aliasing?) has also been fixed. No more rough cats here :-)

**Comment by win0err** [comment]
Version 6: https://extensions.gnome.org/extension/2986/runcat/
