### ISSUE TITLE
We need Gnome 40 Support

### ISSUE THREAD

**Issue by lqs01** [win0err/gnome-runcat#11]
I need my cat back. ;)

**Comment by win0err** [comment]
Let me guess, you're an Arch Linux user ;-)

GNOME 40 dropped GTK3 support, I'm testing an update to GTK4 with backward compatibility with 3.36 and 3.38.
I will fix it in a week

**Comment by lqs01** [comment]
Hey thank you. :D

....and I use Arch btw. ;)

**Comment by win0err** [comment]
Published a new version to EGO. It's [under review](https://extensions.gnome.org/review/23338) now, will be available in few days.
