### ISSUE TITLE
Destination directory

### ISSUE THREAD

**Issue by igor-dyatlov** [win0err/gnome-runcat#12]
Adding the ability to change the location of the target directory.

If you run the command `sudo make install` then the installation will be in _/usr/share/gnome-shell/extensions_

After approval, I can send pull https://github.com/igor-dyatlov/gnome-runcat/commit/161153238cd74dd8673d377d308adbe03ba7d078

**Comment by win0err** [comment]
Why do you need a system-wide extension?

Copying [dash-to-doc's Makefile](https://github.com/micheleg/dash-to-dock/blob/master/Makefile) with lots of garbage code is a 100% bad idea.

I see two ways of solving your problem:
1. Packaging (.deb, .rpm, etc)
2. Adding `install-system` (`cp build/ /usr/share/gnome-shell/extensions/gnome-runcat`) and `uninstall-system` (`rm -rf /usr/share/gnome-shell/extensions/gnome-runcat`) goals in Makefile — I'll add these goals for you

**Comment by igor-dyatlov** [comment]
Yes, the Makefile from this extension.

I believe that the code is not junk, but informative and ready for any user tasks. Also, how often is Makefile used?)
I close issue.
