### ISSUE TITLE
Percentage text and animation doesn't scale well

### ISSUE THREAD

**Issue by abhaypatil2000** [win0err/gnome-runcat#13]
I have set the scaling factor to 1.25 in gnome tweaks > fonts > scaling factor. All the extensions and text scale well, except runcat.

![Screenshot from 2021-04-10 03-15-35](https://user-images.githubusercontent.com/56753048/114243898-15417200-99ab-11eb-9d3d-4cd9960a38be.png)

**Comment by win0err** [comment]
Thank you for the issue, @abhaypatil2000. I'll fix that, thank you

**Comment by CuriousApe2020** [comment]
I have a similar issue where the Cat is very small on "Dash to Panel" when the Pc starts until i turn the extension off an on again.

**Comment by abhaypatil2000** [comment]
> I have a similar issue where the Cat is very small on "Dash to Panel" when the Pc starts until i turn the extension off an on again.

Sadly that didn't work for me. How do you turn off and on the extension.? I did it through gnome extensions app. Did you do it the same way?

**Comment by win0err** [comment]
> > I have a similar issue where the Cat is very small on "Dash to Panel" when the Pc starts until i turn the extension off an on again.
> 
> Sadly that didn't work for me. How do you turn off and on the extension.? I did it through gnome extensions app. Did you do it the same way?

I fixed the issue, I'll deliver the changes in the next release ;-)

**Comment by win0err** [comment]
Fixed in 87f6fec90d659e88225422fdb4d8cf6f154bebd3
