### ISSUE TITLE
runcat after screen inactivity

### ISSUE THREAD

**Issue by Gohub007** [win0err/gnome-runcat#14]
runcat stops running after the screen went dark by gnome power settings, have to restart runcat in the gnome extension once again. not so after a suspend of the linux box

**Comment by win0err** [comment]
Hi! Which system including gnome versions do you use?

**Comment by Gohub007** [comment]
Hi there, we are running it on EndeavourOS Linux 5.11.15-arch1-2 with Gnome 40.0-1 actually first I thought it may be caused by wireless network but today after a resume on wired network I had to restart it again. It seems sometimes just stop working, sometimes after resume sometimes after the screen went black. I keep a eye on it.

**Comment by hparlak** [comment]
I have the same problem with Fedora 34 + Gnome 40.0.0

**Comment by hparlak** [comment]
Thanks to you too. This happened after I upgraded from Fedora 33 to 
Fedora34, by the way.

**Comment by prasadpatil25** [comment]
Facing the same issue, I freshly installed Fedora 34 (Gnome 40).

**Comment by Rafablues94** [comment]
Happens the same to me in Fedora 34 (Gnome 40)

**Comment by win0err** [comment]
@Rafablues94, @prasadpatil25, @Gohub007, @hparlak: does the issue still occur?

**Comment by Rafablues94** [comment]
Yeah, it keeps happening. Last time was today after a reboot, the percent showed 0 until I disabled and enabled the extension.

**Comment by prasadpatil25** [comment]
It can be reproduced after putting the computer to sleep and waking it up again.

**Comment by win0err** [comment]
Please, check an updated version on extensions.gnome.org — v12 was not available for GNOME 40.1.

**Comment by snoopakon** [comment]
A quick fix (and temporal fix) can be to restart the extension when double-clicked.

**Comment by Elinvention** [comment]
I have the same issue and this error message pops up in the logs:
```
JS ERROR: Error: Argument interval: value is out of range for uint32
_addTimeout@/home/elia/.local/share/gnome-shell/extensions/runcat@kolesnikov.se/timer.js:38:28
_tick@/home/elia/.local/share/gnome-shell/extensions/runcat@kolesnikov.se/timer.js:33:14
_addTimeout/this.timeout<@/home/elia/.local/share/gnome-shell/extensions/runcat@kolesnikov.se/timer.js:38:83
```

**Comment by KaboomPhysicist** [comment]
I still have the same issue after update. Where or how can i see the logs?

**Comment by flicker211** [comment]
> @Elinvention, @KaboomPhysicist, @prasadpatil25, @Rafablues94, @hparlak, @Gohub007, I've released version 15 with a probable fix of the issue. It will be available in a couple of days on extensions.gnome.org. Please, send some feedback about the issue in the new release.
> 
> P.S. @Elinvention, thank you for the error message! P.P.S. Available on https://extensions.gnome.org/extension/2986/runcat/
is it out yet? cuz i redownloaded it and ive still got the issue

**Comment by win0err** [comment]
> > @Elinvention, @KaboomPhysicist, @prasadpatil25, @Rafablues94, @hparlak, @Gohub007, I've released version 15 with a probable fix of the issue. It will be available in a couple of days on extensions.gnome.org. Please, send some feedback about the issue in the new release.
> > P.S. @Elinvention, thank you for the error message! P.P.S. Available on https://extensions.gnome.org/extension/2986/runcat/
> 
> is it out yet? cuz i redownloaded it and ive still got the issue

New version is available only for GNOME 3.38, 40 and 41

**Comment by win0err** [comment]
> I still have the same issue after update. This is the message in the logs:
> 
> ```
> JS ERROR: Error: Argument interval: value is out of range for uint32
> _addTimeout@/home/cs/.local/share/gnome-shell/extensions/runcat@kolesnikov.se/timer.js:38:28
> _tick@/home/cs/.local/share/gnome-shell/extensions/runcat@kolesnikov.se/timer.js:33:14
> _addTimeout/this.timeout<@/home/cs/.local/share/gnome-shell/extensions/runcat@kolesnikov.se/timer.js:38:83
> ```
> 
> The extension works after restarting the Gnome Shell, but it keeps freezing after a suspension or log out.
> 
> Gnome version: 40.4.0

Thank you, I'll keep trying to fix the issue

**Comment by win0err** [comment]
@Netherquark, @KaboomPhysicist, @Gohub007: please, install v17 from https://extensions.gnome.org/extension/2986/runcat/. If the bug will happen again, please, reopen the issue

**Comment by win0err** [comment]
Thanks @nirfse for testing!
