### ISSUE TITLE
RunCat shows as "INCOMPATIBLE" for Gnome 40.1 on extensions.gnome.org

### ISSUE THREAD

**Issue by shawnbrown** [win0err/gnome-runcat#15]
Gnome version 40.1 has recently landed. But RunCat's [shell-version](https://github.com/win0err/gnome-runcat/blob/7338b4472986cd69134f4b6369189c94ce3a1380/src/metadata.json#L5-L9) only includes up to "40.0" so it's now listed as "INCOMPATIBLE" for distros running the latest Gnome.

Current RunCat listing for Gnome 40.1 users:

> ![RunCat-Gnome-40 1](https://user-images.githubusercontent.com/69084/120224186-f2944280-c210-11eb-98c1-99770760da0b.png)

**Comment by win0err** [comment]
@shawnbrown, thank you! I'll release a new version as soon as possible!

**Comment by shawnbrown** [comment]
I don't know if it's advisable, but the extensions that simply listed a `shell-version` of `"40"` instead of `"40.0"` did not have this issue.

Of course, doing that means you can't guarantee that it won't break in a future Gnome update (since the Gnome project does _not_ follow [Semantic Versioning](https://semver.org/)).

**Comment by win0err** [comment]
Fun fact. 

When GNOME 40.0 just released, some extension's developers added `"40"` (not `"40.0"`) to the `shell-version` field, according to [GNOME blog, section Version validation](https://blogs.gnome.org/shell-dev/2021/03/12/gnome-40-your-extension/)... and users was unable to install these extensions from the GNOME Extensions website (this bug was fixed).

**Comment by shawnbrown** [comment]
That's annoying. You could probably just list them all `40`,  `40.0`, `40.1`.

**Comment by win0err** [comment]
Fixed in 67da37b991ad949e818519d248fb255759d6dfc1; already availabe at [extensions.gnome.org](https://extensions.gnome.org/extension/2986/runcat/)

**Comment by shawnbrown** [comment]
This is confirmed to be working!

I successfully installed it on Fedora 34 running Gnome 40.1.
