### ISSUE TITLE
Update stops and restarts randomly on Gnome 40.4.0

### ISSUE THREAD

**Issue by ask6483** [win0err/gnome-runcat#17]
On Gnome 40.4.0 I noticed updating issue, extension seems to stop and restart updating itself randomly.
Load string is also trimmed at percentage sign and returns back to normal when clicked anywhere at the top bar.
I tried to take a screenshot but this operation also fixes the problem.

Debian bookworm, Gnome 40.4.0

**Comment by win0err** [comment]
Thanks, will dig in to the issue!
