### ISSUE TITLE
Launch gnome-system-monitor on click

### ISSUE THREAD

**Issue by Raqbit** [win0err/gnome-runcat#18]
I think it would be cool if you could click the cat to launch gnome-system-monitor with the resources tab open (`-r` commandline option), to get more detailed info on cpu usage as a quick shortcut.

**Comment by ashrude** [comment]
This would be pretty cool. There could also be a setting to change the command in case people prefer something else like htop

**Comment by win0err** [comment]
@Raqbit, @ashrude, thank you for the feedback. 

Yeah, that's a really good idea. 
I will implement this feature soon!

**Comment by win0err** [comment]
Added in https://github.com/win0err/gnome-runcat/pull/32, released in v20:
![image](https://user-images.githubusercontent.com/11278181/193626862-b7bc6795-17d2-4103-a5f6-563eea3dc996.png)
