### ISSUE TITLE
cat keep sleep when I run a docker container

### ISSUE THREAD

**Issue by everyx** [win0err/gnome-runcat#19]
![图片](https://user-images.githubusercontent.com/1665522/142391501-20755e23-4732-4fde-907e-e41442a44bbc.png)

![2021-11-18 17-45-13屏幕截图](https://user-images.githubusercontent.com/1665522/142391434-acd396e6-1f6a-45cd-9588-b34650f2db6e.png)

**Comment by win0err** [comment]
Hello, @everyx! Could you reproduce the bug on version 17?

This version is available on https://extensions.gnome.org/extension/2986/runcat/

![image](https://user-images.githubusercontent.com/11278181/151846072-473d9fd3-31c9-4c1f-962a-754dd6591d88.png)

**Comment by everyx** [comment]
> Hello, @everyx! Could you reproduce the bug on version 17?
> 
> This version is available on https://extensions.gnome.org/extension/2986/runcat/
> 
> ![image](https://user-images.githubusercontent.com/11278181/151846072-473d9fd3-31c9-4c1f-962a-754dd6591d88.png)

@win0err  It's looks like get work again now, thanks.
