### ISSUE TITLE
Add options other than the cat

### ISSUE THREAD

**Issue by benzea** [win0err/gnome-runcat#2]
It being a GNOME extension, I think there should also be a wanda the fish and Gegl (Genetically Large Engineered Goat).

Possibly one or both only as easter eggs :)

**Comment by win0err** [comment]
Thank you for your feedback!
I like your idea, especially about GEGL :-) 

I'll add new runners in the future.

**Comment by nlpsuge** [comment]
@win0err 

Perhaps it's wonderful if the user can change corlor?

**Comment by win0err** [comment]
> @win0err
> 
> Perhaps it's wonderful if the user can change corlor?

Thank you for your feedback. 
It's a good idea, but as far as I know, it's not a simple task.

**Comment by benzea** [comment]
> It's a good idea, but as far as I know, it's not a simple task.

If you are using symbolic icons, then I suspect all you need to do is to change the font colour for the containing widget.

**Comment by UlyssesZh** [comment]
[RunCat_for_windows](/Kyome22/RunCat_for_windows) offers parrot and horse.
