### ISSUE TITLE
Broken settings window appearance on Gnome 42.rc

### ISSUE THREAD

**Issue by ry755** [win0err/gnome-runcat#26]
After forcing this extension to install on Gnome 42.rc by adding "42" to metadata.json, the settings window looks wrong. The settings themselves still work, they just look a bit scrunched :P
Other than this cosmetic issue, the rest of the extension seems to work properly without any extra changes.

![image](https://user-images.githubusercontent.com/23299242/159179501-12e545f6-4e2e-48b0-b348-0c65795bac32.png)

![image](https://user-images.githubusercontent.com/23299242/159179524-67ac0b10-6c2d-4c73-9fcd-f8b734aca843.png)

**Comment by win0err** [comment]
Hello!

Fixed by @luavixen. 
I published a new version on [extensions.gnome.org](extensions.gnome.org), will be available soon.

**Comment by ry755** [comment]
Awesome, thank you!!
