### ISSUE TITLE
Version 18 breaks in GNOME 41.3

### ISSUE THREAD

**Issue by yatli** [win0err/gnome-runcat#28]

**Comment by win0err** [comment]
Hello, thanks for the issue!

Thanks, I'll check.
Have you tried logging out and then logging back in (or just restart GNOME Shell)?

**Comment by yatli** [comment]
Ooh, thanks for that! I'll try to install the extension again.

btw Really Cute (TM)

**Comment by win0err** [comment]
If it helps, please, close the issue

**Comment by yatli** [comment]
Confirmed. Installing the extension from a fresh boot works as expected.
Thanks!
