### ISSUE TITLE
Stopped working after the recent update

### ISSUE THREAD

**Issue by MyfIvm** [win0err/gnome-runcat#4]
Gnome 3.34. Everything was fine till the recent update. Now it doesn't work with the following message:

JS ERROR: Extension runcat@kolesnikov.se: Error: Type name Gjs_PanelMenuButton is already registered
_init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/overrides/GObject.js:385:24
registerClass@resource:///org/gnome/gjs/modules/overrides/GObject.js:94:12
@/home/pha/.local/share/gnome-shell/extensions/runcat@kolesnikov.se/panelMenuButton.js:12:23
@/home/pha/.local/share/gnome-shell/extensions/runcat@kolesnikov.se/extension.js:6:7
_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:348:13
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:278:22
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:244:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:108:13

Please let me know if I can provide more details.

**Comment by MyfIvm** [comment]
Checked out the v6 branch and replaced the files manually. It works. v7 doesn't :(

**Comment by win0err** [comment]
@MyfIvm, which OS and its version do you use?

**Comment by MyfIvm** [comment]
Ubuntu 19.10

**Comment by win0err** [comment]
@MyfIvm, thanks!

Fixed in 5b52783
