### ISSUE TITLE
Merging v22 feature branch

### ISSUE THREAD

**Issue by jakob30061** [win0err/gnome-runcat#45]
Hey  @win0err,
while thinking about adding multiple runner support to your extension, i saw there is already a PR merged.

Do you intent releasing these features?

Best regards

**Comment by win0err** [comment]
Hello, @jakob30061!

Sorry for late response. 

I plan to draw 2 more runners (cats — that’s important) and then release a new version

**Comment by jakob30061** [comment]
Alright, no worries!
If I can help with something, I would be happy to do so.

Best Regards
