### ISSUE TITLE
A "sleeping" threshold

### ISSUE THREAD

**Issue by MyfIvm** [win0err/gnome-runcat#5]
Now the poor cat has to run permanently, even if the CPU load is 1 - 2 - 3%.
What if some simple setting is implemented, make the cat sleeping for the low values of CPU load?
Let's say, a checkbox "sleep under 5%" or a input field "sleep under [...] %".

P.S. That is a great idea, such a widget. Thanks.

**Comment by win0err** [comment]
@MyfIvm, thank you for your feedback!

Currently I'm working over new update which adds new settings like sleeping threshold, show/hide percentage, etc. 

Stay tuned! :-)

**Comment by ask6483** [comment]
Any news about this update?

**Comment by win0err** [comment]
> Any news about this update?

Hello, @ask6483! 

@bouteillerAlan made a PR with this update. Also, I'm implementing an ability to hide cat or percentage value.
Those changes will appear in the next release.
